version: '3'
services:
  gfg-db:
    image: mysql
    ports:
      - "3307:3306"
    env_file:
      - evs.env    
  gfg-web:
    image: nginx    
    ports:
      - "8088:80" 
    depends_on:
      - gfg-db